In [151]:
import numpy as np #one sample of a T out of 50, also need 50 Ls
A = np.array([[1,1,1,0],
             [0,1,0,0],
             [0,1,0,0],
             [0,1,0,0]])
print(A.shape)

(4, 4)


In [152]:
v = A.reshape(-1)

In [153]:
print(v)

[1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0]


In [154]:
L = np.array([[1,0,0,0],
             [1,0,0,0],
             [1,0,0,0],
             [1,1,1,0]])

In [155]:
print(L)

[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 1 0]]


In [156]:
# for label
#-1 and +1

In [157]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt

In [158]:
import numpy as np
import random

def generate_L():
    grid = np.zeros((4,4), dtype=int)

    # choose position
    row = random.randint(0, 2)
    col = random.randint(0, 2)

    # choose vertical and horizontal lengths (at least 2)
    vert_len = random.randint(2, 4 - row)
    horiz_len = random.randint(2, 4 - col)

    # vertical leg
    for r in range(row, row + vert_len):
        grid[r][col] = 1
    # horizontal leg (attached at bottom of vertical)
    for c in range(col, col + horiz_len):
        grid[row + vert_len - 1][c] = 1

    return grid

def generate_T():
    grid = np.zeros((4,4), dtype=int)

    # choose top row
    row = random.randint(0, 2)
    col = random.randint(0, 1)

    horiz_len = random.randint(2, min(4 - col, 4))
    vert_len = random.randint(2, 4 - row)

    # horizontal bar
    for c in range(col, col + horiz_len):
        grid[row][c] = 1
    # vertical stem from middle of horizontal
    mid = col + horiz_len // 2
    for r in range(row, row + vert_len):
        grid[r][mid] = 1

    return grid

# generate datasets
L_shapes = [generate_L() for _ in range(50)]
T_shapes = [generate_T() for _ in range(50)]

# print examples
print("Example L shape:\n", L_shapes[0])
print("\nExample T shape:\n", T_shapes[0])

Example L shape:
 [[1 0 0 0]
 [1 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Example T shape:
 [[0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 1 0]]


In [159]:
list_epochs_loss = []

def fit(X_train, y_train):
    learning_rate = 0.1

    n_samples, n_features = X_train.shape

    weights = np.zeros(n_features)
    bias = 0

    for _ in range(1000):
        epoch_loss = []

        for idx, x_i in enumerate(X_train):

            linear_product = np.dot(x_i, weights) + bias
            y_pred = np.sign(linear_product)

            if y_pred == 0:
                y_pred = -1

            # Perceptron update rule
            if y_train[idx] * y_pred <= 0:
                weights += learning_rate * y_train[idx] * x_i
                bias    += learning_rate * y_train[idx]
                epoch_loss.append(1)
            else:
                epoch_loss.append(0)

        avg = sum(epoch_loss) / len(epoch_loss)
        list_epochs_loss.append(avg)

    return weights, bias

In [160]:


def activation_function(z):
    return np.where( z>=0, 1, 0  )



In [161]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [162]:
X_train = X_train.reshape(X_train.shape[0], -1)

In [163]:
X_train = X_train.reshape(X_train.shape[0], -1)
X_test  = X_test.reshape(X_test.shape[0], -1)

weights, bias = fit(X_train, y_train)

In [164]:
activation_function(2.5)

array(1)

In [165]:


def accuracy(y_true, y_pred):
    accuracy = np.sum(   y_true == y_pred   ) / len(  y_true  )
    return accuracy



In [166]:
y_test

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1])

In [167]:
print(accuracy(y_pred, y_test))

0.55
